require:
- rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 20
