version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: ruby:2.6.5

    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check
      - ruby/rspec-test
